# Generated by Django 5.1.2 on 2024-10-16 22:24
from django.db import migrations, models
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('media_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media_images')),
            ],
        ),
    ]
