# Generated by Django 5.1.2 on 2024-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('media_type', models.CharField(max_length=50)),
                ('local_image', models.ImageField(default='media/media_images/film.png', upload_to='media')),
                ('film_image', models.ImageField(default='media/media_images/film.png', upload_to='media')),
                ('other_image', models.ImageField(blank=True, default='media/media_images/film.png', null=True, upload_to='media')),
                ('general_info', models.TextField()),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
    ]
