# Generated by Django 5.1.2 on 2024-10-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='image',
        ),
    ]
