# Generated by Django 5.1.2 on 2024-10-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_mediaitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(default='media/media_images/film.png', upload_to='media'),
        ),
    ]
